name: Deploy Azure Function (Oryx, Plan Flexible OK)

on:
  push:
    branches:
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure (Oryx build)
        run: |
          az functionapp deployment source config \
            --name ${{ secrets.AZURE_FUNCTIONAPP_NAME }} \
            --resource-group ${{ secrets.AZURE_RG }} \
            --repo-url https://github.com/${{ github.repository }} \
            --branch prod \
            --manual-integration


